site_name: ACI Automation Training
site_description: Welcome to our ACI Automation Training with Practice Lab

nav:
  - Home: index.md
  - Lab Access:
    - Accessing the Lab Environment: LAB_access.md
  - Day1 LAB sections:
    - Install and operate Postman: postman.md
    - Automation basis with restAPI: restAPI.md
    - Create customer use-cases with Postman: use-cases-postman.md
    - How to pull informations using restAPI: monitor-aci.md
  - Day2 LAB sections:
    - Terraform setup: terraform-installation.md
    - Terraform basic deployment: terraform-basis.md
    - Terraform variables: terraform-vars.md
    - Terraform modules: terraform-modules.md
    - Terraform state: terraform-state.md
  - Appendixes:
    - dCloudGuacamole: guacamole.md
    - Resources: resources.md
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
